# Generated by Django 4.1.7 on 2023-03-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_rentingcanvas_rentingshelves_alter_contacts_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='comentar',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Коментар'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comentar',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Коментар'),
        ),
        migrations.AddField(
            model_name='rentingcanvas',
            name='comentar',
            field=models.TextField(default='', max_length=1000, verbose_name='Коментар'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentingshelves',
            name='comentar',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Коментар'),
        ),
    ]
