# Generated by Django 4.1.7 on 2023-03-13 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_contacts_comentar_feedback_comentar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasRentedDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_id', models.IntegerField(default=0, verbose_name='ID стелажа')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('comentar', models.TextField(max_length=1000, verbose_name='Коментар')),
                ('date_from', models.DateField(default=datetime.date.today)),
                ('date_to', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name_plural': '(Зарезервовані) Оренда полотна',
            },
        ),
        migrations.CreateModel(
            name='ShelvesRentedDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelves_id', models.IntegerField(default=0, verbose_name='ID стелажа')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('comentar', models.TextField(max_length=1000, verbose_name='Коментар')),
                ('date_from', models.DateField(default=datetime.date.today)),
                ('date_to', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name_plural': '(Зарезервовані) Оренда стелажів',
            },
        ),
        migrations.AlterModelOptions(
            name='rentingcanvas',
            options={'verbose_name_plural': '(Запити) Оренда полотна'},
        ),
        migrations.AlterModelOptions(
            name='rentingshelves',
            options={'verbose_name_plural': '(Запити) Оренда стелажів'},
        ),
        migrations.RemoveField(
            model_name='rentingcanvas',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='rentingshelves',
            name='rate',
        ),
        migrations.AddField(
            model_name='rentingcanvas',
            name='canvas_id',
            field=models.IntegerField(default=0, verbose_name='ID полотна'),
        ),
        migrations.AddField(
            model_name='rentingshelves',
            name='shelves_id',
            field=models.IntegerField(default=0, verbose_name='ID стелажа'),
        ),
    ]
