# Generated by Django 4.1.7 on 2023-03-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topnews',
            name='title',
        ),
        migrations.AlterField(
            model_name='topnews',
            name='short_description',
            field=models.TextField(max_length=500),
        ),
    ]
