# Generated by Django 4.1.7 on 2023-03-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_remove_topnews_title_alter_topnews_short_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'Новини'},
        ),
        migrations.AlterModelOptions(
            name='topnews',
            options={'verbose_name_plural': 'Новини - слайди'},
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='news',
            name='full_description',
            field=models.TextField(blank=True, null=True, verbose_name='Повний опис'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='topnews',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='topnews',
            name='short_description',
            field=models.TextField(max_length=500, verbose_name='Короткий опис'),
        ),
    ]
