# Generated by Django 4.1.7 on 2023-03-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_news_options_alter_topnews_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Короткий опис')),
                ('full_description', models.TextField(blank=True, null=True, verbose_name='Повний опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='action/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name_plural': 'Події',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Короткий опис')),
                ('full_description', models.TextField(blank=True, null=True, verbose_name='Повний опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='music/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name_plural': 'Музика',
            },
        ),
    ]
