# Generated by Django 4.1.7 on 2023-03-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='invoiceId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
