# Generated by Django 4.1.7 on 2023-03-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_orders_invoiceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='invoiceId',
            field=models.CharField(max_length=255),
        ),
    ]
