# Generated by Django 4.1.7 on 2023-03-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_orders_invoiceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orderPayType',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='orderPosterCreateCheck',
            field=models.BooleanField(default=False),
        ),
    ]
