# Generated by Django 4.1.7 on 2023-03-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_orders_orderpaytype_orders_orderpostercreatecheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orderTransactionId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
