# Generated by Django 4.1.7 on 2023-03-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_orders_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderTransactionId',
            field=models.IntegerField(blank=True),
        ),
    ]
