# Generated by Django 4.1.7 on 2023-03-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_orders_ordertransactionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderTransactionId',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
