# Generated by Django 4.1.7 on 2023-03-06 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_orders_ordertransactionid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'Замовлення !НЕ РЕДАГУВАТИ!'},
        ),
    ]
